name: to_goling_mvp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # iOS ìŠ¤íƒ€ì¼ ì•„ì´ì½˜
  cupertino_icons: ^1.0.8

  # ğŸ“ ìœ„ì¹˜ ì„œë¹„ìŠ¤ (Geolocator)
  geolocator: ^13.0.1

  # ğŸ’¾ ë¡œì»¬ ì €ì¥ì†Œ (SharedPreferences)
  shared_preferences: ^2.2.3

  # ğŸ“² NFC ì½ê¸° (MVPì—ì„œëŠ” ê¸°ë³¸ ë¹„í™œì„±)
  nfc_manager: ^3.3.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
